### ISSUE TITLE
Classes undefined

### ISSUE THREAD

**Issue by rub256** [creativetimofficial/material-kit-react#14]
I am trying to use your project into mine but always have the same problems.

classes are undefined. 
Debugging I can see that the objects coming for imports (for example: Header) never exists.

Some tip about can solve this?

Thanks.

**Comment by EINazare** [comment]
Hello again @rub256 ,

Thank you for opening this issue here.
Can you please make me a screenshot with the errors from the top in your console?

Best,
Manu

**Comment by rub256** [comment]
Hello,

As i Said I am using my own project. I Have to set all  the routes and I can navigate to the files.
I am really new with react but I think about the problem is that I forgot to add something really required in my package.json.

My Folder structure
![captura de pantalla 2018-05-29 a las 23 05 46](https://user-images.githubusercontent.com/5639986/40685598-fc1558b8-6394-11e8-93c7-d087f4721a09.png)

How I am setting the imports

![captura de pantalla 2018-05-29 a las 23 06 40](https://user-images.githubusercontent.com/5639986/40685615-09cfe086-6395-11e8-9031-4064f1737e9e.png)

My Package dependencies / Scripts

![captura de pantalla 2018-05-29 a las 23 08 03](https://user-images.githubusercontent.com/5639986/40685674-316b0cf6-6395-11e8-839c-7c14eba491b8.png)


And finally my problem.

![captura de pantalla 2018-05-29 a las 23 01 40](https://user-images.githubusercontent.com/5639986/40685413-826cca64-6394-11e8-8954-857015c6f7b9.png)


![captura de pantalla 2018-05-29 a las 23 02 29](https://user-images.githubusercontent.com/5639986/40685414-82c6abba-6394-11e8-8536-3a527cdd8c43.png)


Really thanks for your help.

**Comment by EINazare** [comment]
Are you exporting your component using `withStyles` ?
Another thing, could you install instead of material-ui/core@1.1.0 the one that you found in our package.json?
Not sure how to help you, i think looking at your code would help me find the problem, but unfortunately i do not have really much time right now to help you with this.
Maybe the community will help you with this one.

Best,
Manu

**Comment by rub256** [comment]
> Are you exporting your component using withStyles ?

Yes I am doing it.

> Another thing, could you install instead of material-ui/core@1.1.0 the one that you found in our package.json?

At the start, I was using material-ui/styles/withStyles as I found in your package.json but I have the following error: _withStyles is not a function. Then the community recommend yo me to use material-ui/core@1.1.0.

**Comment by EINazare** [comment]
In a few days/weeks we are going to update our product to material-ui latest version, and may e than you will not have this issue anymore.

**Comment by EINazare** [comment]
Hello @rub256 ,

Is this still a problem for you?
Have you figured out what the problem was?

Best,
Manu

**Comment by rub256** [comment]
Yes, I can not solved.

I think is something relate with sass, but I can not find the problem.

**Comment by EINazare** [comment]
I do not know what the problem could be.
Is it possible for me to get your project and make some tests? 
I am asking this because i am going to make an update tomorrow on this product, and i would like to see if this is something that can be fixed within our product or not.

Best,
Manu

**Comment by rub256** [comment]
Yes, of course. 

I prepare this test repository for you. 
Thanks for all.

**Comment by EINazare** [comment]
Hello @rub256 ,

Just found out what the problems are:
First of all, you make the imports like this: `import { Header } from "../components/Header/Header.jsx";`, and this is wrong because we do not have an export in our components, we have a default export, so you need to change those imports from that of the above to `import Header from "../components/Header/Header.jsx";`

Than, you have in `src/LoginPage/LoginPage.jsx` at the end of the file the following code:
```
const connectedLoginPage = connect(mapStateToProps)(LoginPage);
export { connectedLoginPage as LoginPage };
export default withStyles(loginPageStyle)(LoginPage);
```
If you delete the `export { connectedLoginPage as LoginPage };` than all errors stop showing.
The problem is that you make two exports there (one with `withStyles`) and another one with the above deletion, you export the same thing, in two ways, and i think there is the main issue.
I do not know if i can make any modifications on our product to solve this issue, since we need `withStyles` to add the styles on our components.
I've made another test by replacing `export { connectedLoginPage as LoginPage };` with `export { connectedLoginPage };` and once again, everything worked fine.
Again, the problem is that you export two things with the same name.

Best,
Manu

**Comment by rub256** [comment]
Hello @EINazare,

Really thanks, at least now we can now the issue. 
It will be nice if we can find some solution about the exports.

Best,
Rub.

**Comment by EINazare** [comment]
I am not sure why you do this `export { connectedLoginPage as LoginPage };`. I think you should have something different here, since at the end of the file you export again the LoginPage but with `withStyles`, (`export default withStyles(loginPageStyle)(LoginPage);`).

**Comment by rub256** [comment]
I am sorry, I was out for a while.
Yes, it was my own mistake, I solved, the correct is as you said: export default withStyles(loginPageStyle)(LoginPage);

Thanks for your help.
