### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by softmarshmallow** [creativetimofficial/material-kit-react#16]
in package.json

```
"dependencies": {
    "@material-ui/core": "^1.2.1",
    "@material-ui/icons": "^1.1.0",
    "material-kit-react": "git+https://github.com/creativetimofficial/material-kit-react.git",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-scripts": "1.1.4"
  },
```

in component
`import Button from "material-kit-react/src/components/CustomButtons/Button";
`

in component.render
`<Button type="button" color="primary">Primary</Button>
`

error is..

> Failed to compile.

> ./node_modules/material-kit-react/src/components/CustomButtons/Button.jsx
> Module parse failed: Unexpected token (15:25)
> You may need an appropriate loader to handle this file type.
> | import buttonStyle from "assets/jss/material-kit-react/components/buttonStyle.jsx";
> | 
> | function RegularButton({ ...props }) {
> |   const {
> |     classes,

whats wrong with here?

**Comment by EINazare** [comment]
Hello @softmarshmallow ,

Thank you for your interest in using our product and for giving us this warning.
It seems that our product needs some changes so it can be used as a npmjs package.
While we are working on that (i am guessing it will take us somewhere around a month, since we are currently working on some other products, and i am going to take a 2 week vacation) you can just download/clone the product and use it as is.

Best,
Manu

**Comment by go2ready** [comment]
Same issue here with npmjs, love to see it fixed!
