### ISSUE TITLE
Build error - routes/index.jsx cannot be resolved 

### ISSUE THREAD

**Issue by niteshp27** [creativetimofficial/material-kit-react#21]
Sorry my bad, the issue is for Material React kit and opened it on HTML version, earlier.
File present in the location but error says its not resolved
Anything to do with node version? v7.9.0

![image](https://user-images.githubusercontent.com/907553/42077131-7d90264e-7b95-11e8-9f73-6151a13906af.png)

![image](https://user-images.githubusercontent.com/907553/42077188-a55c42a2-7b95-11e8-8b24-af33c0a368a4.png)

**Comment by EINazare** [comment]
Hello @niteshp27 ,

Thank you for your interest in using our product.
Did you make any changes to our product?
Can you try installing the latest versions of NodeJs and NPM?

Best,
Manu

**Comment by EINazare** [comment]
Hello again @niteshp27 ,

Is this still an issue?

Best,
Manu

**Comment by dualeoo** [comment]
Hi @EINazare !

I managed to fix it. The problem is not because I didn't use latest version of the product, npm, or NodeJS. The problem is that I did not successfully integrate the kit to my existing project.

When I started fresh (simply use the kit + npm install + npm start), things work perfectly. The error did not occur. When I tried to copy and paste files from the kit to my current project, the error occurs.

So the bottom line is: if you want to use the kit, start fresh or copy your files to the kit 😄 

Btw, Thank you for your fast response!

Minh

**Comment by EINazare** [comment]
Hello @dualeoo ,

I am glad that everything worked in the end.

Best,
Manu

**Comment by moconchobhair** [comment]
FYI if anyone else runs into this issue. I struggled with it for a while and eventually found that thanks to a .gitignore file filtering .env files (and some git pain) I didn't have the .env in the root of my project, which is required for react-scripts to work properly.

**Comment by DharaniRenu1** [comment]
please, give the version of node and npm because me too getting the same error..
