### ISSUE TITLE
Very slow to Edit and Compile a  Page

### ISSUE THREAD

**Issue by jainmanoj** [creativetimofficial/material-kit-react#39]
Hi,

I am trying to use the  basic themes for one of the project.
I am building a display panel with few components on it.
The problem is for a very simple modification it compile the whole bundle including the kit.
The process is very slow to use it this way (Takes 2 mins sometimes)
I would like to know - how I can make faster development
Thanks
Manoj

**Comment by EINazare** [comment]
Hello there @jainmanoj ,

And thank you for your interest in using our product.
I am not sure what the problem is, for me is quite simple what the solution is.
Just take what you need from our product, and that way you won't have any problems.
Also, I believe that you should not have deleted our ISSUES_TEMPLATE.
Maybe I haven't understood your problem, and my solution is not what you are seeking for.
So, please, next time, just use the ISSUES_TEMPLATE.
```
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.
```


Best,
Manu
