### ISSUE TITLE
Horizontal TImeLine 

### ISSUE THREAD

**Issue by shashical** [creativetimofficial/material-kit-react#47]
Am looking for reactJS Horizontal time line and i have checked in this material kit react.
Can any one help me to get UI + ReactJs Horizontal Time Line

**Comment by EINazare** [comment]
Hello there @shashical ,

Thank you for your interest in working with our product.
You can access this [link here](https://github.com/creativetimofficial/material-kit-react/archive/master.zip), and the download of this product should start right away.
Or you can download the product from [our platform](https://www.creative-tim.com/product/material-kit-react).
I do not understand what 
>  ReactJs Horizontal Time Line

stands for in your comment.

Hope this information helps you.

Best,
Manu

**Comment by shashical** [comment]
Hello @EINazare 
Thank you for your reply. 
I wanted to add bellow Time Line Code to Material UI 
https://www.npmjs.com/package/react-horizontal-timeline

**Comment by EINazare** [comment]
Hello again @shashical ,

We have some sort of that plugin in our PRO paid product.
Here are our examples: 

- [https://demos.creative-tim.com/material-dashboard-pro-react/#/forms/wizard](https://demos.creative-tim.com/material-dashboard-pro-react/#/forms/wizard)
- [https://demos.creative-tim.com/material-dashboard-pro-react/#/timeline-page](https://demos.creative-tim.com/material-dashboard-pro-react/#/timeline-page)

The first one is a wizard component, but it is made dynamically, with clicks on the nav tabs, and the second is a static example, but with a bit of work, you can make it dynamic as well.

Anyways, we cannot help you with the integration of the given plugin in our product, since we already have something like that in our PRO paid version, but I am pretty sure that the integration is not that hard.

I will leave your issue opened so that others see it, and maybe come to your help.

Best,
Manu

**Comment by shashical** [comment]
I wanted to buy this product.
What are the things am getting in this product.
Am looking for mainly reactJS + performance should be good.
Will i get all source code ?
Is possible to connect aws API calls linking with this product if its there
need help once i buy.
https://demos.creative-tim.com/material-dashboard-pro-react/#/forms/wizard

**Comment by shashical** [comment]
Its a start up company what is the cost of Pro Paid Product?

**Comment by shashical** [comment]
Actually am looking for HEALTH CARE Data displaying and It should be
attractive UI
IF any UI if u know please refer me

**Comment by shashical** [comment]
I have checked in Basic Material Kit in that i did not get list of items
examples
Can any one help me

**Comment by EINazare** [comment]
Hello again @shashical ,

I am not sure what to tell you to do.
I most definitely do not want to advise you to buy any of our products, that way, if you are not satisfied with it, then the blame would be on me.
I can only say, that you can take any of our [FREE react products](https://www.creative-tim.com/bootstrap-themes/react-themes) and see if they suit your needs so you can decide if you buy or not, any of our PRO paid versions.

Best,
Manu
