### ISSUE TITLE
Pricing page does not change on click

### ISSUE THREAD

**Issue by Northshoot** [creativetimofficial/material-kit-react#48]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

Page
https://demos.creative-tim.com/material-kit-pro-react/#/sections#pricing

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

After clicking "Get Started" I expect that pricing section to become selected.

# Current Behavior

Nothing happens

# Failure Information (for bugs)

No info available 

## Steps to Reproduce

1. go to https://demos.creative-tim.com/material-kit-pro-react/#/sections#pricing
2. click "get started"
3. enjoy nothing happening

## Context

Same is happening whether on a local setup or on your website demo site.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by EINazare** [comment]
Hello there @Northshoot ,

Thank you for your interest in working with our products.
Since this is a template product, it is normal behavior.
Those are Sections for you to get started easily creating a new page. The functionality of those buttons should be added by you, maybe you want to make an Ajax call to your server, or maybe you want to open a modal, the choice is yours, we've only given you the design, an example on how it should look like a pricing section in your page.

Hope this information helps you.

I can see that you have checked two checkboxes, and left two of them blank.
Why did you not open this issue to the correct repository?
Why aren't you running the latest version?

Best,
Manu

**Comment by Northshoot** [comment]
I understand the backend part.

What I would expect is that the highlight of the component would change after the click.

**Comment by EINazare** [comment]
Hello again, @Northshoot ,

I am going to discuss this with the board.

Best,
Manu
