### ISSUE TITLE
is this them support RTL

### ISSUE THREAD

**Issue by aminsource** [creativetimofficial/material-kit-react#50]
is this theme support RTL?, if yes how configure it for RTL support?

**Comment by EINazare** [comment]
Hello there @aminsource ,

Thank you for your interest in working with this product.
There are some components that have rtl configuration, but since it is a FREE product, the number of rtl components is small.
Anyway, please check our live docs to learn more about this: https://demos.creative-tim.com/material-kit-react/#/documentation/tutorial

Best,
Manu

**Comment by aminsource** [comment]
Thx is any discount for this kits?:)

**Comment by EINazare** [comment]
Hello again, @aminsource ,

At the moment, I see on our [platform](https://www.creative-tim.com/) that there is no discount only for the Material Kit PRO React.
I know that you get a discount if you buy the React Bundle instead of paying $597 for 6 products you only pay $149, which I believe is a huge discount.

Best,
Manu
