### ISSUE TITLE
Feature Request: Support for Gatsby

### ISSUE THREAD

**Issue by ozskywalker** [creativetimofficial/material-kit-react#51]
Am about to purchase both the material kit pro react & dashboard to support some project work I'm doing, but I'm having to hack the current free version (this repo) to support Gatsby.   

While that's OK for my current project, but would it be possible if you could include instructions or a fork which would make it a lot easier in the future?

**Comment by atonb117** [comment]
Ditto.

I need to use React for a couple projects and would love some guidance on the best way to integrate your kits with Gatsby.

I have wired up both free (Get Shit Done) and pro kits (NowUI) in the past to various node backends but a guide for Gatsby would be great.

**Comment by EINazare** [comment]
Hello there @atonb117 ,

Thank you for your interest in working with our products.
We'll see what we can do.

Best,
Manu

**Comment by ajmueller** [comment]
@ozskywalker @atonb117 I'm in the process of evaluating this project for use with Gatsby and just got it working.  Here's a quick rundown of the process I followed and the resources I used in the hopes that it saves you some time.  For reference, I used the default Gatsby starter.

1. Add `@material-ui/core`, `@material-ui/icons`, and `classnames` to your dependencies.
2. You need a module resolver that allows you to reference the `assets` and `components` directories without using relative paths since this is how all paths are referenced in the source.  You can use [gatsby-plugin-resolve-src](https://www.gatsbyjs.org/packages/gatsby-plugin-resolve-src/?=resolver) to *resolve* this issue 😄 If you want something with some more fine-grained control, [gatsby-plugin-module-resolver](https://www.gatsbyjs.org/packages/gatsby-plugin-module-resolver/?=resolver) is a good option, too.
3. You also need Sass support and [gatsby-plugin-sass](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/?=sass) is a simple way to get this.  Also make sure to install `node-sass` as a dependency.
4. Copy the `assets` and `components` directories into the `src` directory.
5. Import the main SCSS file in `src/pages/index.js` by adding `import "assets/scss/material-kit-react.scss?v=1.4.0"` (naturally replacing the `v` query string param with your version.
6. Add [gatsby-plugin-material-ui](https://github.com/hupe1980/gatsby-plugin-material-ui).  This will fix any flashes of unstyled content you may get on full pages built with Material Kit React.
7. At this point you should be able to build pages as you like with Material Kit React.  A good way to test this is to take one of the `views` directories, e.g. `LandingPage` and copy it into the `pages` directory in Gatsby, renaming it to something like `landing`.  Then visit `/landing/` in your browser and you should see the landing page example.

If you run into any issues, let me know.  You'll also find that there are [some starters that use Material](https://www.gatsbyjs.org/starters/?s=material&v=2) that may be helpful, particularly [gatsby-material-kit-react](https://www.gatsbyjs.org/starters/WebCu/gatsby-material-kit-react/).  This kit basically does what I described above and was a big help in figuring out how to integrate Material Kit React into Gatsby, so a big thanks to @WebCu for that.  Since I plan on using Material Kit React Pro with Gatsby, I wanted to go through the process myself, though.

Hope this helps.

**Comment by alanpog** [comment]
@EINazare, I've bought the `PRO` version with the hope of using it with Gatsby.

However, I have followed @ajmueller 's instructions above and while everything works fine with  gatsby in *development* mode when I *build* it the final result flashes, for a good part of a second it seems, a lot of "ugly" unstyled stuff. This is only the first time per route, after which the cache seems to be enough to prevent it.

You can actually see this happening with the demo for @WebCu 's [gatsby-material-kit-react starter](https://www.gatsbyjs.org/starters/WebCu/gatsby-material-kit-react/). To reproduce it, just open the [demo link](https://amazing-jones-e61bda.netlify.com/) in a new incognito/private window. I've tested with chrome, safari and firefox on a mac.

Any help or hint of what I can try to do to fix this is appreciated.

**Comment by eddiebeazer** [comment]
That final flash is because is the CSS being injected into the dom.  The flash happens when the static str version of the site is loaded, the flash then appears as the browser copy is loaded.  Not sure if I explained that properly.  Adding [gatsby-plugin-material-ui](https://github.com/hupe1980/gatsby-plugin-material-ui) should fix it.  I used that repo as a base for my Gatsby project, let me know if you have any issues.

**Comment by alanpog** [comment]
@eddiebeazer I was using `gatsby-plugin-material-ui` already, I found the issue thanks to your prompt and will explain what was happening in case it can help someone else. 

Your suggestion made me take another look at the plugin config and I was, [per the current install instructions on their github page](https://github.com/hupe1980/gatsby-plugin-material-ui), using the `@next` version (`2.00-alpha`). I switched to the `@latest` one (`1.2.4`) and now it works fine. Thanks!

**Comment by WebCu** [comment]
@ajmueller Thanks for your words. I really like the description of the process to adapt Material-UI to Gatsby that you did. Do you mean if I add it to the description of gatsby-material-kit-react?

Thanks @alanpog and @eddiebeazer for the investigation about the problem of the "ugly" unstyled stuff :) I'll do the modifications suggested by you and see how works with gatsby-material-kit-react.

**Comment by ajmueller** [comment]
@WebCu I don't mind at all!  Please feel free to adapt or directly use my instructions as you see fit.

**Comment by ptrobert** [comment]
@ajmueller @alanpog  can any of you post a workng repo with "initial load (gibberish) problem solved"

**Comment by ptrobert** [comment]
@ajmueller @alanpog Never mind, I followed your suggestions , its working

**Comment by ptrobert** [comment]
@ajmueller @alanpog  I am in process of adding pro version to gatsby, started facing issues with window object. In some cases i removed the refering button etc and some of them were moved to component did mount, did you guys managed to get a decent gatsby site working with pro version

**Comment by ajmueller** [comment]
@ptrobert no, sorry, I never ended up buying the pro version.  We’re just building our own basic component system now.

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2.0.0 and now it contains a totally new structure with a new and fresh design.

**All the best**
**Sajad**
