### ISSUE TITLE
Feature Request: Support react-boilerplate

### ISSUE THREAD

**Issue by kentdev92** [creativetimofficial/material-kit-react#64]
I have bought Material UI Kit Pro, 
I'm very excited with this template, it's very clean, easy to understand and also maintain.
But in your document, right now it's explain only how can i integrate into create-react-app(it's single page application).
And I'm really really want you guys can help me and also other new developers to create a guide explain how we can integrate this UI into react-boilerplate, because it's SSR. And some situations, it's better than SPA like: SEO, split loadable,...

Best regards @timcreative. Once again, thank you guys so much for created amazing UI kit!

**Comment by EINazare** [comment]
This issue was closed due to the fact that it did not comply with our rules: 
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/material-kit-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
Also, there are some question marks about the product used:
- The issue is opened on the Material Kit React: https://www.creative-tim.com/product/material-kit-react
- The issue refers to the Material Kit PRO (HTML version - `I have bought Material UI Kit Pro,`): https://www.creative-tim.com/product/material-kit-pro

If you need help with your development, please open a ticket on our contact us form here: https://www.creative-tim.com/contact-us
Choose the `I want to hire you for a custom project/website/design` option.
You will be given some contacts that can help you - this is because we are not doing client based projects.
